FROM node:20.12.2 AS build
WORKDIR /app
RUN apt-get update && \
    apt-get install -y python3 make g++ && \
    apt-get clean
COPY . .
RUN npm install
RUN npm run build -- --configuration production

FROM nginx:alpine
COPY --from=build /app/dist/developer-store/browser /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf